default: &default
  application_name: GoogleDirectoryDaemon-test
  application_id: gdd-t

  admin_user_id: alexandre.narbonne@poubs.org
  authorizer: DefaultAuthorizer

  message_handler_map:
    request.gapps.create: CreateUserMessageHandler

  rabbitmq_queue_name: gapps2
  rabbitmq_exchange_name: agoram_event_exchange
  rabbitmq_deferred_time: 1000
  rabbitmq_max_attempts: 48

  log_routing_key: "agoram.log"

  gram_api_host: http://api.dev.gadz.org/api/v1
  gram_api_user: ratatosk
  gram_api_password: YPuLNNul


development:
  <<: *default

test:
  <<: *default

production:
  <<: *default